---
kind: pipeline
name: default

services:
  - name: minio
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    command: 
      - server
      - /data
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey

workspace:
  base: /go
  path: src/github.com/mobilusoss/go-s3fs

steps:
  - name: test
    image: golang
    commands:
      - go get -v github.com/golang/dep/...
      - $GOPATH/bin/dep ensure
      - go test -race -coverprofile=coverage.txt -covermode=atomic
  - name: codecov
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN