language: go
sudo: required
go:
  - 1.12
  - tip
services:
  - docker
before_install:
  - docker run -d --name minio -e 'MINIO_ACCESS_KEY=accesskey' -e 'MINIO_SECRET_KEY=secretkey' -p 9000:9000 minio/minio:RELEASE.2018-12-27T18-33-08Z server /data
  - go get github.com/golang/dep/...
install:
  - $GOPATH/bin/dep ensure
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)